-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateCountryInfoRequiredArguments =
    { input : Api.InputObject.CreateCountryInfoInput }


{-| Creates a single `CountryInfo`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createCountryInfo :
    CreateCountryInfoRequiredArguments
    -> SelectionSet decodesTo Api.Object.CreateCountryInfoPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createCountryInfo requiredArgs____ object____ =
    Object.selectionForCompositeField "createCountryInfo" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeCreateCountryInfoInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateTransactionRequiredArguments =
    { input : Api.InputObject.CreateTransactionInput }


{-| Creates a single `Transaction`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createTransaction :
    CreateTransactionRequiredArguments
    -> SelectionSet decodesTo Api.Object.CreateTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createTransaction requiredArgs____ object____ =
    Object.selectionForCompositeField "createTransaction" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeCreateTransactionInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateUserRequiredArguments =
    { input : Api.InputObject.CreateUserInput }


{-| Creates a single `User`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createUser :
    CreateUserRequiredArguments
    -> SelectionSet decodesTo Api.Object.CreateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createUser requiredArgs____ object____ =
    Object.selectionForCompositeField "createUser" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeCreateUserInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateWeatherDatumRequiredArguments =
    { input : Api.InputObject.CreateWeatherDatumInput }


{-| Creates a single `WeatherDatum`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createWeatherDatum :
    CreateWeatherDatumRequiredArguments
    -> SelectionSet decodesTo Api.Object.CreateWeatherDatumPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createWeatherDatum requiredArgs____ object____ =
    Object.selectionForCompositeField "createWeatherDatum" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeCreateWeatherDatumInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateCountryInfoRequiredArguments =
    { input : Api.InputObject.UpdateCountryInfoInput }


{-| Updates a single `CountryInfo` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateCountryInfo :
    UpdateCountryInfoRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateCountryInfoPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateCountryInfo requiredArgs____ object____ =
    Object.selectionForCompositeField "updateCountryInfo" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateCountryInfoInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateCountryInfoByIdRequiredArguments =
    { input : Api.InputObject.UpdateCountryInfoByIdInput }


{-| Updates a single `CountryInfo` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateCountryInfoById :
    UpdateCountryInfoByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateCountryInfoPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateCountryInfoById requiredArgs____ object____ =
    Object.selectionForCompositeField "updateCountryInfoById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateCountryInfoByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateTransactionRequiredArguments =
    { input : Api.InputObject.UpdateTransactionInput }


{-| Updates a single `Transaction` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateTransaction :
    UpdateTransactionRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateTransaction requiredArgs____ object____ =
    Object.selectionForCompositeField "updateTransaction" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateTransactionInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateTransactionByIdRequiredArguments =
    { input : Api.InputObject.UpdateTransactionByIdInput }


{-| Updates a single `Transaction` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateTransactionById :
    UpdateTransactionByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateTransactionById requiredArgs____ object____ =
    Object.selectionForCompositeField "updateTransactionById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateTransactionByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateUserRequiredArguments =
    { input : Api.InputObject.UpdateUserInput }


{-| Updates a single `User` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUser :
    UpdateUserRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateUser requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateUserInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateUserByIdRequiredArguments =
    { input : Api.InputObject.UpdateUserByIdInput }


{-| Updates a single `User` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUserById :
    UpdateUserByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateUserById requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUserById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateUserByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateUserByUsernameRequiredArguments =
    { input : Api.InputObject.UpdateUserByUsernameInput }


{-| Updates a single `User` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUserByUsername :
    UpdateUserByUsernameRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateUserByUsername requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUserByUsername" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateUserByUsernameInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateUserByEmailRequiredArguments =
    { input : Api.InputObject.UpdateUserByEmailInput }


{-| Updates a single `User` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUserByEmail :
    UpdateUserByEmailRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateUserByEmail requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUserByEmail" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateUserByEmailInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateWeatherDatumRequiredArguments =
    { input : Api.InputObject.UpdateWeatherDatumInput }


{-| Updates a single `WeatherDatum` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateWeatherDatum :
    UpdateWeatherDatumRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateWeatherDatumPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateWeatherDatum requiredArgs____ object____ =
    Object.selectionForCompositeField "updateWeatherDatum" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateWeatherDatumInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateWeatherDatumByIdRequiredArguments =
    { input : Api.InputObject.UpdateWeatherDatumByIdInput }


{-| Updates a single `WeatherDatum` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateWeatherDatumById :
    UpdateWeatherDatumByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.UpdateWeatherDatumPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateWeatherDatumById requiredArgs____ object____ =
    Object.selectionForCompositeField "updateWeatherDatumById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeUpdateWeatherDatumByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteCountryInfoRequiredArguments =
    { input : Api.InputObject.DeleteCountryInfoInput }


{-| Deletes a single `CountryInfo` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteCountryInfo :
    DeleteCountryInfoRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteCountryInfoPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteCountryInfo requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteCountryInfo" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteCountryInfoInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteCountryInfoByIdRequiredArguments =
    { input : Api.InputObject.DeleteCountryInfoByIdInput }


{-| Deletes a single `CountryInfo` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteCountryInfoById :
    DeleteCountryInfoByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteCountryInfoPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteCountryInfoById requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteCountryInfoById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteCountryInfoByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteTransactionRequiredArguments =
    { input : Api.InputObject.DeleteTransactionInput }


{-| Deletes a single `Transaction` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteTransaction :
    DeleteTransactionRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteTransaction requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteTransaction" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteTransactionInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteTransactionByIdRequiredArguments =
    { input : Api.InputObject.DeleteTransactionByIdInput }


{-| Deletes a single `Transaction` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteTransactionById :
    DeleteTransactionByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteTransactionById requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteTransactionById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteTransactionByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteUserRequiredArguments =
    { input : Api.InputObject.DeleteUserInput }


{-| Deletes a single `User` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUser :
    DeleteUserRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteUser requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteUser" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteUserInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteUserByIdRequiredArguments =
    { input : Api.InputObject.DeleteUserByIdInput }


{-| Deletes a single `User` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUserById :
    DeleteUserByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteUserById requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteUserById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteUserByIdInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteUserByUsernameRequiredArguments =
    { input : Api.InputObject.DeleteUserByUsernameInput }


{-| Deletes a single `User` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUserByUsername :
    DeleteUserByUsernameRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteUserByUsername requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteUserByUsername" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteUserByUsernameInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteUserByEmailRequiredArguments =
    { input : Api.InputObject.DeleteUserByEmailInput }


{-| Deletes a single `User` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUserByEmail :
    DeleteUserByEmailRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteUserByEmail requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteUserByEmail" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteUserByEmailInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteWeatherDatumRequiredArguments =
    { input : Api.InputObject.DeleteWeatherDatumInput }


{-| Deletes a single `WeatherDatum` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteWeatherDatum :
    DeleteWeatherDatumRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteWeatherDatumPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteWeatherDatum requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteWeatherDatum" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteWeatherDatumInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteWeatherDatumByIdRequiredArguments =
    { input : Api.InputObject.DeleteWeatherDatumByIdInput }


{-| Deletes a single `WeatherDatum` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteWeatherDatumById :
    DeleteWeatherDatumByIdRequiredArguments
    -> SelectionSet decodesTo Api.Object.DeleteWeatherDatumPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteWeatherDatumById requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteWeatherDatumById" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeDeleteWeatherDatumByIdInput ] object____ (Basics.identity >> Decode.nullable)
