-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type CountryInfo
    = CountryInfo


type CountryInfosConnection
    = CountryInfosConnection


type CountryInfosEdge
    = CountryInfosEdge


type CreateCountryInfoPayload
    = CreateCountryInfoPayload


type CreateTransactionPayload
    = CreateTransactionPayload


type CreateUserPayload
    = CreateUserPayload


type CreateWeatherDatumPayload
    = CreateWeatherDatumPayload


type DeleteCountryInfoPayload
    = DeleteCountryInfoPayload


type DeleteTransactionPayload
    = DeleteTransactionPayload


type DeleteUserPayload
    = DeleteUserPayload


type DeleteWeatherDatumPayload
    = DeleteWeatherDatumPayload


type PageInfo
    = PageInfo


type Transaction
    = Transaction


type TransactionsConnection
    = TransactionsConnection


type TransactionsEdge
    = TransactionsEdge


type UpdateCountryInfoPayload
    = UpdateCountryInfoPayload


type UpdateTransactionPayload
    = UpdateTransactionPayload


type UpdateUserPayload
    = UpdateUserPayload


type UpdateWeatherDatumPayload
    = UpdateWeatherDatumPayload


type User
    = User


type UsersConnection
    = UsersConnection


type UsersEdge
    = UsersEdge


type WeatherDataConnection
    = WeatherDataConnection


type WeatherDataEdge
    = WeatherDataEdge


type WeatherDatum
    = WeatherDatum
