-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias BigFloat =
    Api.Scalar.BigFloat


type alias Cursor =
    Api.Scalar.Cursor


type alias Datetime =
    Api.Scalar.Datetime


type alias Id =
    Api.Scalar.Id


codecs : Api.Scalar.Codecs BigFloat Cursor Datetime Id
codecs =
    Api.Scalar.defineCodecs
        { codecBigFloat = defaultCodecs.codecBigFloat
        , codecCursor = defaultCodecs.codecCursor
        , codecDatetime = defaultCodecs.codecDatetime
        , codecId = defaultCodecs.codecId
        }
