-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CountryInfo exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A globally unique identifier. Can be used in various places throughout the system to identify this single value.
-}
nodeId : SelectionSet Api.ScalarCodecs.Id Api.Object.CountryInfo
nodeId =
    Object.selectionForField "ScalarCodecs.Id" "nodeId" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


id : SelectionSet Int Api.Object.CountryInfo
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Api.Object.CountryInfo
name =
    Object.selectionForField "String" "name" [] Decode.string


capital : SelectionSet String Api.Object.CountryInfo
capital =
    Object.selectionForField "String" "capital" [] Decode.string


phoneCode : SelectionSet String Api.Object.CountryInfo
phoneCode =
    Object.selectionForField "String" "phoneCode" [] Decode.string
