-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.UpdateCountryInfoPayload exposing (..)

import Api.Enum.CountryInfosOrderBy
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The exact same `clientMutationId` that was provided in the mutation input,
unchanged and unused. May be used by a client to track mutations.
-}
clientMutationId : SelectionSet (Maybe String) Api.Object.UpdateCountryInfoPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The `CountryInfo` that was updated by this mutation.
-}
countryInfo :
    SelectionSet decodesTo Api.Object.CountryInfo
    -> SelectionSet (Maybe decodesTo) Api.Object.UpdateCountryInfoPayload
countryInfo object____ =
    Object.selectionForCompositeField "countryInfo" [] object____ (Basics.identity >> Decode.nullable)


{-| Our root query field type. Allows us to run any query from our mutation payload.
-}
query :
    SelectionSet decodesTo RootQuery
    -> SelectionSet (Maybe decodesTo) Api.Object.UpdateCountryInfoPayload
query object____ =
    Object.selectionForCompositeField "query" [] object____ (Basics.identity >> Decode.nullable)


type alias CountryInfoEdgeOptionalArguments =
    { orderBy : OptionalArgument (List Api.Enum.CountryInfosOrderBy.CountryInfosOrderBy) }


{-| An edge for our `CountryInfo`. May be used by Relay 1.

  - orderBy - The method to use when ordering `CountryInfo`.

-}
countryInfoEdge :
    (CountryInfoEdgeOptionalArguments -> CountryInfoEdgeOptionalArguments)
    -> SelectionSet decodesTo Api.Object.CountryInfosEdge
    -> SelectionSet (Maybe decodesTo) Api.Object.UpdateCountryInfoPayload
countryInfoEdge fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy (Encode.enum Api.Enum.CountryInfosOrderBy.toString |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "countryInfoEdge" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
