-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.WeatherDataConnection exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of `WeatherDatum` objects.
-}
nodes :
    SelectionSet decodesTo Api.Object.WeatherDatum
    -> SelectionSet (List (Maybe decodesTo)) Api.Object.WeatherDataConnection
nodes object____ =
    Object.selectionForCompositeField "nodes" [] object____ (Basics.identity >> Decode.nullable >> Decode.list)


{-| A list of edges which contains the `WeatherDatum` and cursor to aid in pagination.
-}
edges :
    SelectionSet decodesTo Api.Object.WeatherDataEdge
    -> SelectionSet (List decodesTo) Api.Object.WeatherDataConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.list)


{-| Information to aid in pagination.
-}
pageInfo :
    SelectionSet decodesTo Api.Object.PageInfo
    -> SelectionSet decodesTo Api.Object.WeatherDataConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity


{-| The count of _all_ `WeatherDatum` you could get from the connection.
-}
totalCount : SelectionSet Int Api.Object.WeatherDataConnection
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int
