-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.UsersOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Methods to use when ordering `User`.
-}
type UsersOrderBy
    = Natural
    | IdAsc
    | IdDesc
    | UsernameAsc
    | UsernameDesc
    | EmailAsc
    | EmailDesc
    | CreatedAtAsc
    | CreatedAtDesc
    | PrimaryKeyAsc
    | PrimaryKeyDesc


list : List UsersOrderBy
list =
    [ Natural, IdAsc, IdDesc, UsernameAsc, UsernameDesc, EmailAsc, EmailDesc, CreatedAtAsc, CreatedAtDesc, PrimaryKeyAsc, PrimaryKeyDesc ]


decoder : Decoder UsersOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NATURAL" ->
                        Decode.succeed Natural

                    "ID_ASC" ->
                        Decode.succeed IdAsc

                    "ID_DESC" ->
                        Decode.succeed IdDesc

                    "USERNAME_ASC" ->
                        Decode.succeed UsernameAsc

                    "USERNAME_DESC" ->
                        Decode.succeed UsernameDesc

                    "EMAIL_ASC" ->
                        Decode.succeed EmailAsc

                    "EMAIL_DESC" ->
                        Decode.succeed EmailDesc

                    "CREATED_AT_ASC" ->
                        Decode.succeed CreatedAtAsc

                    "CREATED_AT_DESC" ->
                        Decode.succeed CreatedAtDesc

                    "PRIMARY_KEY_ASC" ->
                        Decode.succeed PrimaryKeyAsc

                    "PRIMARY_KEY_DESC" ->
                        Decode.succeed PrimaryKeyDesc

                    _ ->
                        Decode.fail ("Invalid UsersOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : UsersOrderBy -> String
toString enum____ =
    case enum____ of
        Natural ->
            "NATURAL"

        IdAsc ->
            "ID_ASC"

        IdDesc ->
            "ID_DESC"

        UsernameAsc ->
            "USERNAME_ASC"

        UsernameDesc ->
            "USERNAME_DESC"

        EmailAsc ->
            "EMAIL_ASC"

        EmailDesc ->
            "EMAIL_DESC"

        CreatedAtAsc ->
            "CREATED_AT_ASC"

        CreatedAtDesc ->
            "CREATED_AT_DESC"

        PrimaryKeyAsc ->
            "PRIMARY_KEY_ASC"

        PrimaryKeyDesc ->
            "PRIMARY_KEY_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe UsersOrderBy
fromString enumString____ =
    case enumString____ of
        "NATURAL" ->
            Just Natural

        "ID_ASC" ->
            Just IdAsc

        "ID_DESC" ->
            Just IdDesc

        "USERNAME_ASC" ->
            Just UsernameAsc

        "USERNAME_DESC" ->
            Just UsernameDesc

        "EMAIL_ASC" ->
            Just EmailAsc

        "EMAIL_DESC" ->
            Just EmailDesc

        "CREATED_AT_ASC" ->
            Just CreatedAtAsc

        "CREATED_AT_DESC" ->
            Just CreatedAtDesc

        "PRIMARY_KEY_ASC" ->
            Just PrimaryKeyAsc

        "PRIMARY_KEY_DESC" ->
            Just PrimaryKeyDesc

        _ ->
            Nothing
